# Site settings
title: Abhishek
description: 'Deep Learning Professional'
url: 'https://naidl.github.io'
baseurl: ''
google_analytics: 'UA-117480447-1'
disqus_shortname: 'naidl-github-io'

author:
  name: 'Abhishek'
  email: abhicoo@gmail.com
  twitter_username: AbhiDroid
  facebook_username: 784803416
  github_username:  naidl
  linkedin_username:  abhishek-kumar-bab92159

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
